// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibeCheckAPI_Dotnet8.Data.Context;

#nullable disable

namespace VibeCheckAPI_Dotnet8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoAvaliacao")
                        .HasColumnType("integer");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Emocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvaliacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ValorNumerico")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("Emocoes");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.RegistroEmocional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmocaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("EmocaoId");

                    b.ToTable("RegistrosEmocionais");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Aluno", b =>
                {
                    b.HasBaseType("VibeCheckAPI_Dotnet8.Models.Usuario");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.HasIndex("TurmaId");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Professor", b =>
                {
                    b.HasBaseType("VibeCheckAPI_Dotnet8.Models.Usuario");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Avaliacao", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Turma", "Turma")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Emocao", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Avaliacao", null)
                        .WithMany("Emocoes")
                        .HasForeignKey("AvaliacaoId");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.RegistroEmocional", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId");

                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Avaliacao", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Emocao", "Emocao")
                        .WithMany()
                        .HasForeignKey("EmocaoId");

                    b.Navigation("Aluno");

                    b.Navigation("Avaliacao");

                    b.Navigation("Emocao");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Turma", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Professor", "Professor")
                        .WithMany("Turmas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Aluno", b =>
                {
                    b.HasOne("VibeCheckAPI_Dotnet8.Models.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Avaliacao", b =>
                {
                    b.Navigation("Emocoes");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("VibeCheckAPI_Dotnet8.Models.Professor", b =>
                {
                    b.Navigation("Turmas");
                });
#pragma warning restore 612, 618
        }
    }
}
